os:
  - linux

dist: xenial
language: cpp

# compilers to add to build matrix
compiler:
  - gcc
  # - clang

addons:
  apt:
    packages:
      - libassimp-dev
      - libsdl2-dev
      - libsdl2-image-dev
#      - libglm-dev    # Wrong CMake target mitigated by CMake config. Package no longer used.
      - libglew-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - cmake --version
  