os:
  - linux

dist: xenial
language: cpp

# compilers to add to build matrix
compiler:
  - gcc
  # - clang

addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libglm-dev
      - libglew-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev libglm-dev libglew-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  - cmake --version
  